version: "3"
services:
    price-calculator-local:
        image: postgres
        restart: always
        container_name: price-calculator-local
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "price-calculator"
            POSTGRES_PASSWORD: "123456"
        ports:
            - "15432:5432"

    zookeeper:
        image: bitnami/zookeeper
        ports:
            - "2181:2181"
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"

    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_CREATE_TOPICS: >-
                good_price_calc_requests:2:1,
                good_price_calc:2:1,
                good_price_calc_requests_dlq:2:1
        ports:
            - "9092:9092"
        expose:
            - 9093
